# Generated by Django 3.2 on 2021-04-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bratool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='users',
        ),
        migrations.RemoveField(
            model_name='historicaldepartment',
            name='users',
        ),
    ]
