# Generated by Django 3.2 on 2021-04-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bratool', '0002_auto_20210420_2329'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='bratool.Department', verbose_name='department'),
        ),
    ]
