# Generated by Django 3.2 on 2021-04-20 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20210420_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='historicalgenre',
            name='tools',
        ),
        migrations.AddField(
            model_name='historicaltool',
            name='genre',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tools.genre', verbose_name='genre'),
        ),
        migrations.AddField(
            model_name='tool',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.genre', verbose_name='genre'),
        ),
    ]
