# Generated by Django 3.2 on 2021-04-24 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bratool', '0002_auto_20210420_2329'),
        ('tools', '0004_auto_20210420_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='bratool.Department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='tools.Genre', verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='keeper'),
        ),
    ]
